nas_user:
  name: nas
users:
  - name: sebschlicht
    smbpasswd: smbtest
    smbdir: sebastian
  - name: isspek
    smbpasswd: smbtest
    smbdir: ipek
  - name: mas
    smbpasswd: smbtest
    smbdir: andrea-michael
