# metadata to exclude steps in certain scenarios
running_in_container: no
uninstall: no

nextcloud:
  version: 20.0.0
  path: /var/www/nextcloud
  data_path: "{{ nas.path }}/nextcloud/data"

dynv6:
  # token to update the current IP address of the NAS domain on DynV6
  password: "{{ vault_dynv6_password }}"

nas_ssh_dir: "/home/{{ nas.user.name }}/.ssh"
sshd:
  # users allowed to SSH into the NAS, in addition to the individual users
  allow_additional_users:
    - "{{ setup_user }}"
    - "{{ nas.user.name }}"
  # enable password-based authentication (strongly discouraged, specify authorized keys per user instead)
  enable_password_authentication: no

server_locales:
  - de_DE.UTF-8
server_timezone: Europe/Berlin

# recipient for administrator mails (e.g. performed upgrades)
mail_recipient: "{{ vault_mail_recipient_address }}"
mailing:
  # mail server connection details
  server: mx2f3e.netcup.net
  port: 465
  # mail server credentials
  user: "{{ vault_mailing_sender_address }}"
  password: "{{ vault_mailing_password }}"
  # custom address / sender name to be used when sending mails
  from_address: "{{ vault_mailing_sender_address }}"
  sender_name: "{{ mailing_sender_name }}"

samba:
  # shares accesible with any account, each having `name` and `path`
  internal_shares:
    - { name: videos, path: "{{ nas.path }}/videos" }
    - { name: secdev, path: "{{ nas.path }}/secdev" }
  # shares accessible with and without an account
  public_shares:
    - { name: software, path: "{{ nas.path }}/software" }

mumble:
  # password required by clients to connect (may be empty)
  password: "{{ vault_mumble_server_password }}"

# OS users for individuals
users:
  - name: sebschlicht
    full_name: Sebastian Schlicht
    mail_address: "{{ vault_sebschlicht_mail_address }}"
    # name of the backup folder (defaults to username)
    backup_folder_name: sebastian
    # hash of the initial password
    initial_password: $6$bvWKhsKfYQL8FH$FBXZZLp2ylLIEFjpj6c7vq.pCaJCH3nn3daYG3kEAhfhOxPoE6Y1kIux9VAiTQ8m1BPbmdYQ7OnCJNgm8h9VE1
    # additional group assignments
    groups: sudo
    samba_password: "{{ vault_sebschlicht_smbpasswd }}"
    nextcloud_user: sebastian
    nextcloud_password: "{{ vault_sebschlicht_nextcloud_password }}"
    authorized_keys:
      - id_sebschlicht.pub
      - id_sebschlicht_mobile.pub
      - id_pi_windows.pub
  - name: isspek
    full_name: Ipek Baris Schlicht
    mail_address: "{{ vault_isspek_mail_address }}"
    backup_folder_name: ipek
    initial_password: $6$AupSaBcLM5QMskO$FOVMKV.xMaNlcGsabZEoI7Hdmk9XxVF0bPBbcn2hsUizL0NQeOiIbdtfZGXDowKaP9acY5iDjIp13Y8upcvRr/
    samba_password: "{{ vault_isspek_smbpasswd }}"
    nextcloud_password: "{{ vault_isspek_nextcloud_password }}"
  - name: mas
    full_name: Michael und Andrea Schlicht
    mail_address: "{{ vault_mas_mail_address }}"
    backup_folder_name: andrea-michael
    initial_password: $6$IieSj6WUcNC$Hlw.UkdS0fqoCaGibNLUCp5sCGm/Jb9KSBWOqtyq6QY.rEPuG5sZyjcYeVqQ0IVdssrUqHK4xgteW3f12S9Fa1
    samba_password: "{{ vault_mas_smbpasswd }}"
    nextcloud_password: "{{ vault_mas_nextcloud_password }}"
    authorized_keys:
      - id_maspc.pub
