nas_user:
  name: nas
users:
  - name: sebschlicht
    password: test
    smbpasswd: smbtest
  - name: isspek
    password: test2
    smbpasswd: smbtest2
  - name: mas
    password: test3
    smbpasswd: smbtest3
