setup_user: sebschlicht

nas:
  hostname: pi
  domain: koblenz.dns.sschlicht.de
  user:
    name: pi
  backup_location: /mnt/nas/primary/backup

mounts:
  primary:
    uuid: 18A302FC66F67B28

mail_recipient: pimon@sschlicht.de

unattended_upgrades:
  notification_mail_recipient: "{{ mail_recipient }}"

mailing:
  server: mx2f3e.netcup.net:465
  user: pi-ko@sschlicht.de
  address: pi-ko@sschlicht.de
  password: "{{ vault_mailing_password }}"
  sender_name: "Pi (Koblenz)"

nextcloud:
  version: 20.0.0
  path: /var/www/nextcloud
  data_path: /mnt/nas/primary/nextcloud/data

samba:
  internal_shares:
    - { name: videos, path: /mnt/nas/primary/videos }
    - { name: secdev, path: /mnt/nas/primary/secdev }
  public_shares:
    - { name: software, path: /mnt/nas/primary/software }

minidlna:
  display_name: SchlichtNAS
  directories:
    - /mnt/nas/primary/videos

dynv6:
  token: "{{ vault_dynv6_token }}"

sshd:
  allow_users:
    - "{{ setup_user }}"

users:
  - name: sebschlicht
    full_name: Sebastian Schlicht
    mail_address: "{{ vault_sebschlicht_mail_address }}"
    backup_folder_name: sebastian
    initial_password: $6$bvWKhsKfYQL8FH$FBXZZLp2ylLIEFjpj6c7vq.pCaJCH3nn3daYG3kEAhfhOxPoE6Y1kIux9VAiTQ8m1BPbmdYQ7OnCJNgm8h9VE1
    groups: sudo
    samba_password: "{{ vault_sebschlicht_smbpasswd }}"
    nextcloud_user: sebastian
    nextcloud_password: "{{ vault_sebschlicht_nextcloud_password }}"
    authorized_keys:
      - id_sebschlicht.pub
      - id_pi_windows.pub
  - name: isspek
    full_name: Ipek Baris Schlicht
    mail_address: "{{ vault_isspek_mail_address }}"
    backup_folder_name: ipek
    initial_password: $6$AupSaBcLM5QMskO$FOVMKV.xMaNlcGsabZEoI7Hdmk9XxVF0bPBbcn2hsUizL0NQeOiIbdtfZGXDowKaP9acY5iDjIp13Y8upcvRr/
    samba_password: "{{ vault_isspek_smbpasswd }}"
    nextcloud_password: "{{ vault_isspek_nextcloud_password }}"
  - name: mas
    full_name: Michael und Andrea Schlicht
    mail_address: "{{ vault_mas_mail_address }}"
    backup_folder_name: andrea-michael
    initial_password: $6$IieSj6WUcNC$Hlw.UkdS0fqoCaGibNLUCp5sCGm/Jb9KSBWOqtyq6QY.rEPuG5sZyjcYeVqQ0IVdssrUqHK4xgteW3f12S9Fa1
    samba_password: "{{ vault_mas_smbpasswd }}"
    nextcloud_password: "{{ vault_mas_nextcloud_password }}"

running_in_container: no
