- name: create backup location
  file:
    path: "{{ nas.backup_location }}"
    state: directory
    owner: "{{ nas.user.name }}"
    group: "{{ nas.user.name }}"
    mode: "{{ nas_backup_directory_mode }}"
    force: yes
  tags: nas

- name: create user backup directories and enforce secure permissions
  file:
    path: "{{ nas.backup_location }}/{{ user.backup_folder_name | default(user.name) }}"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "{{ nas_personal_backup_directory_mode }}"
    force: yes
  loop: "{{ users }}"
  loop_control:
    loop_var: user
  tags: nas
