force_ca_recreation: false
openvpn_ca_folder: "{{ openvpn.ca_folder | default('/opt/openvpn-ca') }}"
openvpn_ca_certificate: "{{ openvpn_ca_folder }}/ca.crt"
openvpn_server_name: "{{ nas.domain | default('server') }}"
openvpn_server_certificate: "{{ openvpn_ca_folder }}/issued/{{ openvpn_server_name }}.crt"
easyrsa_folder: "{{ openvpn.easyrsa_folder | default('/usr/share/easy-rsa') }}"
easyrsa_exe: "{{ easyrsa_folder }}/easyrsa"
