easyrsa_folder: "{{ openvpn.easyrsa_folder | default('/usr/share/easy-rsa') }}"
easyrsa_exe: "{{ easyrsa_folder }}/easyrsa"
openvpn_port: "{{ openvpn.port | default(1194) }}"
openvpn_ca_force_recreation: no
openvpn_ca_folder: "{{ openvpn.ca_folder | default('/opt/openvpn-ca') }}"
openvpn_ca_root_certificate: "{{ openvpn_ca_folder }}/ca.crt"
openvpn_ca_certificate_folder: "{{ openvpn_ca_folder }}/issued"
openvpn_ca_certificate_server: "{{ openvpn_ca_certificate_folder }}/{{ openvpn_server_name }}.crt"
openvpn_server_tls_auth_key: "{{ openvpn_ca_folder }}/ta.key"
openvpn_server_name: "{{ nas.domain | default('server') }}"
openvpn_server_folder: '/etc/openvpn/server'
openvpn_client_folder: '/etc/openvpn/client'
