all:
  children:
    nas:
      hosts:
        192.168.1.4:
          ansible_sudo_pass: "{{ vault_ansible_sudo_pass }}"
          # password of the initial system user to setup passwordless SSH access via playbook `prepare-pi.yml` 
          # ansible_become_pass: myraspberrypw
          # ansible_ssh_pass: myraspberrypw
