version: "3.6"
services: 
  worker:
    build: ./docker
    restart: always
    ports:
      - "49100:22"
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
networks:
  default:
