pis:
  hosts:
    "localhost:49100":
      ansible_user: pi
      ansible_become: yes
      ansible_become_method: sudo
      ansible_become_pass: "{{ pi_sudo_pass }}"
      nas_users:
      - name: sebschlicht
        password: test
      - name: ispek
        password: test2