pis:
  hosts:
    "localhost:49100":
      ansible_user: pi
      ansible_become: yes
      ansible_become_method: sudo
      ansible_become_pass: "{{ pi_sudo_pass }}"
      nas:
        user:
          name: nas
          password: nas
          smbpasswd: smbnas
        mount_base_dir: /mnt/nas
        users:
          - name: sebschlicht
            password: test
            smbpasswd: smbtest
          - name: isspek
            password: test2
            smbpasswd: smbtest2
      samba_users: "{{ nas.users }}"