pis:
  hosts:
    "localhost:49100":
      ansible_user: pi
      ansible_become: yes
      ansible_become_method: sudo
      ansible_become_pass: "{{ pi_sudo_pass }}"
      nas:
        user:
          name: nas
          password: nas
          smbpasswd: smbnas
          shares:
            - name: software
              type: public
              path: /mnt/nas/primary/software
            - name: videos-tv
              type: public
              path: /mnt/nas/primary/videos
        mount_base_dir: /mnt/nas
        users:
          - name: sebschlicht
            password: test
            smbpasswd: smbtest
            shares:
              - name: sebastian
                type: private
                path: /mnt/nas/primary/sebastian
              - name: videos-sebastian
                label: Sebastian's videos
                type: semi-public
                path: /mnt/nas/primary/sebastian/videos
          - name: isspek
            password: test2
            smbpasswd: smbtest2
      samba:
        users: "[{{ nas.user }}] + {{ nas.users }}"