all:
  children:
    dev:
      hosts:
        "localhost:49100":
          ansible_user: pi
          ansible_become: yes
          ansible_become_method: sudo
          ansible_become_pass: "{{ pi_sudo_pass }}"
    prod:
      hosts:
        pi:
          ansible_user: pi
          ansible_become: yes
          ansible_become_method: sudo
          ansible_become_pass: "{{ pi_sudo_pass }}"
