---
- name: Setup the Network Access Storage (NAS)
  hosts: nas
  remote_user: "{{ setup_user }}"
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - role: os
      tags: os
    - role: sshd
      tags: sshd
    - role: ufw
      tags: ufw
    - role: mount
      tags: mount
    - role: userdata
      tags: userdata
    - role: restic
      tags: backup
    - role: auto-upgrade
      tags: auto-upgrade
    - role: dynv6
      tags: ddns
    - role: openvpn-init
      tags: openvpn-init
    - role: openvpn
      tags: openvpn-config
    - role: samba
      tags: samba
    - role: minidlna
      tags: dlna
    - role: mumble
      tags: mumble
    - role: nextcloud
      tags: cloud
    - role: aftercare
      tags: always
