---
- name: Setup the Network Access Storage (NAS)
  hosts: nas
  remote_user: "{{ setup_user }}"
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - role: nas
      tags: nas
    - role: auto-upgrade
      tags: auto-upgrade
    - role: sshd
      tags: sshd
    - role: dynv6
      tags: dyndns
    - role: samba
      tags: smb
    - role: minidlna
      tags: dlna
    - role: ufw
      tags: ufw
    - role: nextcloud
      tags: cloud
