- name: install
  apt:
    name: samba
    state: present

- name: setup users
  include_tasks: user.yml
  loop: "{{ users }}"
  loop_control:
    loop_var: user

- name: configure
  blockinfile:
    path: /etc/samba/smb.conf
    block: "{{ lookup('file', 'smb.conf') }}"
    validate: testparm -s %s

- name: configure service
  service:
    name: smbd
    state: started
    enabled: yes
