- name: install
  apt:
    name: samba
    state: present

- name: setup users
  include_tasks: user.yml
  loop: "{{ samba.users }}"
  loop_control:
    loop_var: user

- name: config
  blockinfile:
    path: /etc/samba/smb.conf
    block: "{{ lookup('file', 'smb.conf') }}"
    validate: testparm -s %s