- name: check user '{{ user.name }}'
  shell: "pdbedit -L | grep '^{{ user.name }}:'"
  register: samba_user_exists
  changed_when: no
  failed_when: "'not found' in samba_user_exists.stdout"
  run_once: yes

- name: create samba user '{{ user.name }}'
  shell: "(echo {{ user.samba.password }}; echo {{ user.samba.password }}) | smbpasswd -s -a {{ user.name }}"
  when: "samba_user_exists.rc == 1"
