- name: install
  apt:
    name:
      - msmtp
      - msmtp-mta
      - bsd-mailx
    cache_valid_time: 600

- name: configure msmtp
  template:
    src: "msmtprc.j2"
    dest: /etc/msmtprc
    owner: root
    group: msmtp
    mode: 0640

- name: set mail alias
  lineinfile:
    path: /etc/aliases
    line: "root:{{ mailing_from }}"
    create: yes
  register: alias

- name: set root name (mail sender)
  shell: "chfn -f '{{ mailing.sender_name }}' root"
  when: alias.changed
