- name: copy script
  template:
    src: dynv6.sh.j2
    dest: /usr/local/bin/dynv6
    mode: 0755
  tags: dynv6

- name: register cronjobs
  cron:
    name: "dynv6 ({{ item }})"
    job: "dynv6 {{ dynv6.hostname }}"
    special_time: "{{ item }}"
  loop:
    - hourly
    - reboot
  tags: dynv6
