- name: install ddclient
  apt:
    name:
      - ddclient
    cache_valid_time: 600

- name: configure ddclient
  copy:
    dest: /etc/ddclient.conf
    content: |
      protocol=dyndns2
      use=web, web=checkip.dyndns.com, web-skip='IP Address'
      server=dynv6.com
      ssl=yes
      login=none
      password='{{ dynv6.password }}'
      {{ nas.domain }}
