- name: ensure required Apache modules are enabled
  import_role:
    name: apache2
    tasks_from: modules.yml
  vars:
    modules:
      - rewrite
      - headers
      - env
      - dir
      - mime

- name: create and enable virtual hosts
  include_role:
    name: apache2
    tasks_from: site.yml
  with_items:
    - nextcloud-le-ssl.conf
  register: apache_sites

- name: restart apache
  service:
    name: apache2
    state: restarted
  when: apache_sites.changed
