- name: configure
  template:
    src: "nextcloud/provisioned.config.php"
    dest: "{{ nextcloud.path }}/config/"
    owner: "{{ apache_user }}"
    group: "{{ apache_user }}"
    mode: 0640
  register: nextcloud_config

- name: make .htaccess writable for occ
  file:
    path: "{{ nextcloud.path }}/.htaccess"
    owner: "{{ apache_user }}"
  when: nextcloud_config.changed

- name: update .htaccess via occ
  shell: |
    sudo -u "{{ apache_user }}" php {{ nextcloud.path }}/occ maintenance:update:htaccess
  when: nextcloud_config.changed

- name: protect .htaccess against modifications
  file:
    path: "{{ nextcloud.path }}/.htaccess"
    owner: root
  when: nextcloud_config.changed

- name: configure background jobs
  shell: |
    sudo -u "{{ apache_user }}" php {{ nextcloud.path }}/occ background:cron
  when: nc_install_path.changed

- name: create users
  include_tasks: user.yml
  with_items: "{{ users }}"
  loop_control:
    loop_var: user
