- name: create installation directory
  file:
    path: "{{ nextcloud.path }}"
    state: directory
  register: nc_install_path

- name: download
  get_url:
    url: "https://download.nextcloud.com/server/releases/nextcloud-{{ nextcloud.version }}.tar.bz2"
    dest: "{{ nc_archive_path }}"
  register: nextcloud_download
  when: nc_install_path.changed

- name: extract
  shell: 'tar -xf "{{ nc_archive_path }}" -C "{{ nextcloud.path }}" --strip 1'
  when: nc_install_path.changed

- name: set base folder permissions
  file:
    path: "{{ nextcloud.path }}"
    owner: root
    group: www-data
    mode: 0750
  when: nc_install_path.changed

- name: create lazy-initialized folders
  file:
    path: "{{ nextcloud.path }}/{{ item }}"
    state: directory
  with_items:
    - assets
  when: nc_install_path.changed

- name: collect Nextcloud files
  find:
    path: "{{ nextcloud.path }}"
    file_type: any
    hidden: yes
    excludes:
      - .htaccess
      - occ
  changed_when: no
  register: nc_files
  when: nc_install_path.changed

- name: set permissions of Nextcloud files
  file:
    path: "{{ item.path }}"
    owner: www-data
    group: www-data
    mode: "u=rw,g=r,o=,a-x+X"
    recurse: "{{ item.isdir }}"
  with_items: "{{ nc_files.files }}"
  when: nc_install_path.changed

- name: set permissions of Nextcloud binaries
  file:
    path: "{{ nextcloud.path }}/occ"
    owner: www-data
    group: www-data
    mode: 0751
  when: nc_install_path.changed

- name: set permissions of htaccess
  file:
    path: "{{ nextcloud.path }}/.htaccess"
    owner: root
    group: www-data
    mode: 0644
  when: nc_install_path.changed

- name: create data directory
  file:
    path: "{{ nextcloud.data_path }}"
    owner: www-data
    group: www-data
    mode: 0750
    state: directory

- name: install
  shell:
    cmd: |
      sudo -u www-data php occ maintenance:install \
        --data-dir '{{ nextcloud.data_path }}' \
        --database 'mysql' --database-name '{{ db_name }}' \
        --database-user '{{ db_user_name }}' --database-pass '{{ db_user_password }}' \
        --admin-user '{{ nc_admin_name }}' --admin-pass '{{ nc_admin_password }}'
    chdir: "{{ nextcloud.path }}"
  when: nc_install_path.changed
  no_log: yes
# TODO try without chdir

- name: configure
  template:
    src: nextcloud/config.php
    dest: "{{ nextcloud.path }}/config/config.php"

# TODO get redis socket (config) working
- name: configure redis socket
  blockinfile:
    block: |
      unixsocket /var/run/redis/redis-server.sock
      unixsocketperm 700
    path: /etc/redis/redis.conf

- name: add web user to redis group
  user:
    name: www-data
    groups: redis
    append: yes

- name: restart apache
  service:
    name: apache2
    state: restarted

# TODO enable mod_rewrite for index.php removal
# TODO template file with OPcache config
# TODO template crontab for www-data

# TODO secure SSL https://doc.owncloud.com/server/admin_manual/installation/letsencrypt/apache.html, esp. ciphers
# TODO check emoji support https://docs.nextcloud.com/server/latest/admin_manual/installation/system_requirements.html#database-requirements-for-mysql-mariadb
