- name: fill database
  import_tasks: mariadb.yml

- name: configure Apache
  import_tasks: apache.yml

- name: install Nextcloud
  import_tasks: install.yml

- name: configure Nextcloud
  import_tasks: config.yml
