- name: create database
  mysql_db:
    name: "{{ db_name }}"
    login_password: "{{ db_root_password }}"

- name: create database user
  mysql_user:
    name: "{{ db_user_name }}"
    password: "{{ db_user_password }}"
    update_password: on_create
    host: localhost
    priv: "{{ db_name }}.*:ALL,GRANT"
    login_password: "{{ db_root_password }}"
  no_log: yes
