- name: install PHP with required modules
  apt:
    name: "{{ item }}"
    cache_valid_time: 600
  with_items:
    - php7.3            # TODO potentially obsolete (maybe still required for php-cli)
    - php7.3-common     # unknown
    - php7.3-curl
    - php7.3-dom
    - php7.3-gd
    - php7.3-intl       # translation performance
    - php7.3-mbstring
    - php7.3-mysql
    - php7.3-xml
    - php7.3-zip
    - php-redis         # caching
    - redis-server
    - php-apcu
    - php-imagick       # previews
    - php7.3-fpm        # threading performance
    - php7.3-bcmath     # Nextcloud performance recommendation
    - php7.3-gmp        # Nextcloud performance recommendation

# TODO file not created before reaching this step!
- name: configure PHP (apache2)
  blockinfile:
    block: "{{ lookup('template', 'php/php.ini.j2') }}"
    dest: "/etc/php/7.3/apache2/php.ini"
    marker: "; {mark} ANSIBLE MANAGED BLOCK"

# TODO file created before reaching this step?
- name: configure php-fpm
  blockinfile:
    block: "{{ lookup('template', 'php/php-fpm.www.conf.j2') }}"
    dest: "/etc/php/7.3/fpm/pool.d/www.conf"
    marker: "; {mark} ANSIBLE MANAGED BLOCK"
