- name: install PHP with required modules
  apt:
    name: "{{ item }}"
    cache_valid_time: 600
  with_items:
    - php7.3
    - php7.3-common     # unknown
    - php7.3-curl
    - php7.3-dom
    - php7.3-gd
    - php7.3-intl       # translation performance
    - php7.3-mbstring
    - php7.3-mysql
    - php7.3-xml
    - php7.3-zip
    - php-redis         # caching
    - redis-server
    - php-apcu
    - php-imagick       # previews

- name: configure PHP
  blockinfile:
    block: "{{ lookup('template', 'php/php.ini.j2') }}"
    dest: "/etc/php/7.3/apache2/php.ini"
