- name: create nas user
  user:
    name: "{{ nas.user.name }}"
    password_lock: yes
    shell: /bin/bash

- name: create SSH directory of nas user
  file:
    path: "{{ nas_ssh_dir }}"
    state: directory
    owner: "{{ nas.user.name }}"
    group: "{{ nas.user.name }}"
    mode: 0700

- name: configure SSH keys of nas user
  copy:
    src: "{{ item }}"
    dest: "{{ nas_ssh_dir }}/"
    owner: "{{ nas.user.name }}"
    group: "{{ nas.user.name }}"
    mode: 0600
  with_items: "{{ nas.ssh_keys }}"

- name: create OS users
  user:
    append: yes
    name: "{{ item.name }}"
    password: "{{ item.initial_password }}"
    groups: "{{ item.groups | default(omit) }}"
  with_items: "{{ users }}"
  loop_control:
    label: "{{ item.name }}"

- name: set hostname
  import_tasks: hostname.yml
  when: not running_in_container

- name: set timezone
  timezone:
    name: "{{ server_timezone }}"
  
- name: set locales
  locale_gen:
    name: "{{ item }}"
  with_items: "{{ server_locales }}"
