- name: create OS users
  user:
    append: yes
    name: "{{ item.name }}"
    password: "{{ item.initial_password }}"
    groups: "{{ item.groups | default(omit) }}"
  with_items: "{{ users }}"
  loop_control:
    label: "{{ item.name }}"

- name: set hostname
  import_tasks: hostname.yml
  when: not running_in_container

- name: set timezone
  timezone:
    name: "{{ server_timezone }}"
  
- name: set locales
  locale_gen:
    name: "{{ item }}"
  with_items: "{{ server_locales }}"
