- name: mount external storage for NAS
  include_tasks: mount.yml
  vars:
    mount: "{{ nas.mount }}"
    mountpoint: "{{ nas.mount.path | default(nas.path) }}"
  when: nas.mount is defined

- name: mount external backup storage for NAS
  include_tasks: mount.yml
  vars:
    mount: "{{ backup.mount }}"
    mountpoint: "{{ backup.mount.path }}"
  when: backup.mount is defined
