- name: check if mounted
  shell: |
    mountpoint -q "{{ mounts_base_dir }}/{{ mount.key }}"
  register: mounted
  changed_when: no
  failed_when: no

- name: create mount point with restrictive permissions
  file:
    path: "{{ mounts_base_dir }}/{{ mount.key }}"
    owner: "{{ nas.user.name }}"
    group: "{{ nas.user.name }}"
    mode: "{{ mount_directory_mode }}"
  when: mounted.rc != 0

- name: "mount {{ mount.key }} NTFS storage device"
  mount:
    path: "{{ mounts_base_dir }}/{{ mount.key }}"
    src: "UUID={{ mount.value.uuid }}"
    state: mounted
    fstype: "{{ mount.value.fstype | default('ntfs-3g') }}"
    opts: "{{ mount.value.opts | default('defaults,windows_names,permissions,nofail,x-systemd.device-timeout=30,locale=de_DE.utf8') }}"
