- name: check if mounted
  shell: |
    mountpoint -q "{{ mountpoint }}"
  register: mounted
  changed_when: no
  failed_when: no

- name: create mount point
  file:
    path: "{{ mountpoint }}"
    state: directory
    mode: "{{ mount_directory_mode }}"
  when: mounted.rc != 0

- name: "mount {{ mountpoint }}"
  mount:
    path: "{{ mountpoint }}"
    src: "UUID={{ mount.uuid }}"
    state: mounted
    fstype: "{{ mount.fstype | default('ntfs-3g') }}"
    opts: "{{ mount.opts | default('defaults,windows_names,permissions,nofail,x-systemd.device-timeout=30,locale=de_DE.utf8') }}"

- name: make mounted device accessible
  file:
    path: "{{ mountpoint }}"
    state: directory
    owner: "{{ nas.user.name }}"
    group: "{{ nas.user.name }}"
    mode: "{{ mount_directory_mode }}"
