- name: install
  apt:
    name:
      - mariadb-server
      - python3-mysqldb # required only for managing the database via Ansible
    cache_valid_time: 600
  register: mariadb_install

- name: secure the installation
  import_tasks: secure_installation.yml
