- name: install
  apt:
    name: ufw
    cache_valid_time: 600

- name: configure defaults
  ufw:
    default: "{{ item.default | default(omit) }}"
    direction: "{{ item.direction | default(omit) }}"
  with_items:
    - default: deny
      direction: incoming
    - default: allow
      direction: outgoing
    
- name: allow SSH communication
  ufw:
    rule: limit
    name: OpenSSH

- name: allow access to Samba
  ufw:
    rule: allow
    name: Samba

- name: allow DLNA communication
  ufw:
    rule: allow
    proto: "{{ item.proto }}"
    to_port: "{{ item.to_port }}"
  with_items:
    - to_port: 8200
      proto: tcp
    - to_port: 1900
      proto: udp

- name: allow HTTP(S) communication
  ufw:
    rule: allow
    proto: tcp
    to_port: 80,443

- name: enable/reload service
  service:
    name: ufw
    state: reloaded
    enabled: yes
  when: not running_in_container
