- name: install
  apt:
    name: ufw
    cache_valid_time: 600

- name: configure defaults
  ufw:
    default: "{{ item.default | default(omit) }}"
    direction: "{{ item.direction | default(omit) }}"
  with_items:
    - default: deny
      direction: incoming
    - default: allow
      direction: outgoing
    
- name: allow SSH communication
  ufw:
    rule: limit
    name: OpenSSH

- name: enable service
  service:
    name: ufw
    enabled: yes
  when: not running_in_container
