- name: configure SSL (apache)
  blockinfile:
    block: "{{ lookup('file', 'options-ssl-apache.conf') }}"
    dest: "/etc/letsencrypt/options-ssl-apache.conf"

- name: remove default HTTP site
  file:
    path: "/etc/apache2/{{ item }}/000-default.conf"
    state: absent
  with_items:
    - sites-enabled
    - sites-available

- name: harden default HTTPS site
  template:
    dest: "/etc/apache2/sites-available/"
    src: apache2/000-default-le-ssl.conf
