- name: install
  apt:
    name: "{{ item }}"
    cache_valid_time: 600
  with_items:
    - certbot
    - python-certbot-apache
  register: certbot_install

# TODO does not certbot create cron entries automatically?

- name: create certificate (Apache)
  shell: "certbot -n --apache --agree-tos -m '{{ certbot.contact_mail_address }}' --domains '{{ certbot.domain }}'"
  when: certbot_install.changed
