- name: install
  apt:
    name:
      - certbot
      - python-certbot-apache
    cache_valid_time: 600
  register: certbot_install

- name: create certificate (Apache)
  shell: "certbot -n --apache --agree-tos -m '{{ certbot.contact_mail_address }}' -d '{{ certbot.domain }}' --redirect"
  when: certbot_install.changed

- name: schedule certificate renewal attempts
  cron:
    job: "/usr/bin/certbot renew --apache -n --agree-tos -m '{{ certbot.contact_mail_address }}' --redirect"
    name: certbot
    special_time: weekly
