- name: install
  apt:
    name: "{{ item }}"
    cache_valid_time: 600
  with_items:
    - certbot
    - python-certbot-apache

# TODO does not certbot create cron entries automatically?

- name: create Apache certificate
  shell: "certbot -n --apache --agree-tos -m '{{ certbot.contact_mail_address }}' --domains '{{ certbot.domain }}'"
