log-append /var/log/openvpn.log
status /var/log/openvpn-status.log 20
status-version 3

# Connection
port 1194
proto udp
dev tun

# Certificates and Keys
ca /etc/openvpn/server/ca.crt
crl-verify /etc/openvpn/server/crl.pem
dh /etc/openvpn/server/dh.pem
cert /etc/openvpn/server/{{ openvpn_server_name }}.crt
key /etc/openvpn/server/{{ openvpn_server_name }}.key

server 10.8.0.0 255.255.255.0
topology subnet
push "dhcp-option DNS 192.168.0.1"
push "block-outside-dns"
push "redirect-gateway def1"

# TLS Security
cipher AES-256-CBC
tls-version-min 1.2
tls-cipher TLS-ECDHE-ECDSA-WITH-AES-256-GCM-SHA384:TLS-ECDHE-ECDSA-WITH-AES-256-CBC-SHA384
auth SHA512
auth-nocache
remote-cert-tls client

# Misc
# duplicate-cn
keepalive 1800 3600
persist-key
persist-tun
compress lz4
daemon
user nobody
group nobody
verb 3
client-to-client
