# Logging
log-append /var/log/openvpn.log
status /var/log/openvpn-status.log 20
status-version 3
verb 3

# Connection
port {{ openvpn_port }}
proto udp
dev tun
keepalive 1800 3600

# Certificates and Keys
ca {{ openvpn_server_folder }}/ca.crt
dh {{ openvpn_server_folder }}/dh.pem
tls-auth {{ openvpn_server_folder }}/ta.key 0
cert {{ openvpn_server_folder }}/{{ openvpn_server_name }}.crt
key {{ openvpn_server_folder }}/{{ openvpn_server_name }}.key

# Networking
server 10.8.0.0 255.255.255.0
topology subnet
push "route 192.168.1.0 255.255.255.0"
push "block-outside-dns"

# TLS Security
cipher AES-256-CBC
tls-version-min 1.2
tls-cipher TLS-ECDHE-ECDSA-WITH-AES-256-GCM-SHA384:TLS-ECDHE-ECDSA-WITH-AES-256-CBC-SHA384
auth SHA512
auth-nocache
remote-cert-tls client

# Permissions
daemon
user openvpn
group openvpn

# Jail
chroot {{ openvpn_server_jail }}
crl-verify crl.pem

# Misc
# duplicate-cn
persist-key
persist-tun
compress lz4
