- name: "Install miniDLNA"
  apt:
    name: "minidlna"
    state: present
- name: Configure miniDLNA
  blockinfile:
    path: "/etc/minidlna.conf"
    block: "{{ lookup('file', 'minidlna.conf') }}"    
- name: "Start miniDLNA"
  service:
    name: "minidlna"
    state: started
    enabled: yes