- name: install
  apt:
    name: minidlna
    cache_valid_time: 600

- name: configure
  blockinfile:
    path: /etc/minidlna.conf
    block: "{{ lookup('template', 'minidlna.conf.j2') }}"
  register: minidlna_config

- name: add miniDLNA user to NAS group
  user:
    name: minidlna
    groups: "{{ nas.user.name }}"

- name: schedule daily re-scan
  cron:
    user: minidlna
    name: reload minidlna for full re-scan
    job: /usr/sbin/minidlnad -R
    hour: 5
    minute: 0

- name: configure firewall
  ufw:
    rule: allow
    proto: "{{ item.proto }}"
    to_port: "{{ item.to_port }}"
  with_items:
    - to_port: 8200
      proto: tcp
    - to_port: 1900
      proto: udp

- name: enable
  service:
    name: minidlna
    state: "{{ minidlna_config.changed | ternary('restarted', 'started') }}"
    enabled: yes
