- name: install
  apt:
    name: minidlna
    cache_valid_time: 600

- name: configure
  blockinfile:
    path: /etc/minidlna.conf
    block: "{{ lookup('template', 'minidlna.conf.j2') }}"

- name: add miniDLNA user to NAS group
  user:
    name: minidlna
    groups: "{{ nas.user.name }}"

- name: schedule daily re-scan
  cron:
    user: minidlna
    name: reload minidlna for full re-scan
    job: /usr/sbin/minidlnad -R
    hour: 6
    minute: 0

- name: start
  service:
    name: minidlna
    state: started
    enabled: yes
