- name: hostname - set
  hostname:
    name: "{{ nas.hostname }}"
  when: "ansible_fqdn != nas.hostname"
  register: hostname

- name: hostname - update hosts file
  lineinfile:
    dest: /etc/hosts
    line: "127.0.1.1\tpi"
    regexp: "^127.0.1.1"
    state: present
  when: hostname.changed
