- name: mailing - install
  apt:
    name:
      - ssmtp
      - mailutils
    cache_valid_time: 600

- name: mailing - configure
  blockinfile:
    path: /etc/ssmtp/ssmtp.conf
    block: "{{ lookup('template', 'etc/ssmtp/ssmtp.conf.j2') }}"

- name: mailing - configure alias
  lineinfile:
    path: /etc/ssmtp/revaliases
    line: "root:{{ mailing.address }}:{{ mailing.server }}"
  register: alias

- name: mailing - configure root name (mail sender)
  shell: "chfn -f '{{ mailing.sender_name }}' root"
  when: alias.changed
