- name: prepare mount point root
  file:
    path: "{{ mount_base_dir }}"
    state: directory
    owner: root
    group: root
    mode: "755"

- name: create UNIX users
  include_tasks: users.yml

- name: mount
  include_tasks: mount.yml
  loop: "{{ mounts }}"
  loop_control:
    loop_var: mount
  when: mounts is defined

- name: file permissions
  block:
    - name: file permissions of private shares
      file:
        path: "{{ mount_base_dir }}/{{ mounts[0].name }}/backup/{{ item.name }}"
        state: directory
        owner: "{{ item.user }}"
        group: "{{ item.user }}"
        mode: '700'
        recurse: yes
      loop:
        - name: sebastian
          user: sebschlicht
        - name: ipek
          user: isspek
        - name: andrea-michael
          user: mas
    - name: file permissions of public shares
      file:
        path: "{{ mount_base_dir }}/{{ mounts[0].name }}/{{ item }}"
        state: directory
        owner: "{{ nas_user.name }}"
        group: "{{ nas_user.name }}"
        recurse: yes
      loop:
        - secdev
        - software
        - videos
