- name: update apt caches
  apt:
    update_cache: yes
  changed_when: no
  tags: nas

- name: prepare mount point root
  file:
    path: "{{ mount_base_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags: nas

- name: create UNIX users
  include_tasks: users.yml
  tags: nas

- name: mount
  include_tasks: mount.yml
  loop: "{{ mounts }}"
  loop_control:
    loop_var: mount
  when: mounts is defined
  tags: nas

- name: file permissions
  block:
    - name: file permissions of private shares
      file:
        path: "{{ mount_base_dir }}/{{ mounts[0].name }}/backup/{{ user.smbdir }}"
        state: directory
        owner: "{{ user.name }}"
        group: "{{ user.name }}"
        mode: 0700
      loop: "{{ users }}"
      loop_control:
        loop_var: user
      tags: nas

    - name: file permissions of public shares
      file:
        path: "{{ mount_base_dir }}/{{ mounts[0].name }}/{{ item }}"
        state: directory
        owner: "{{ nas.user.name }}"
        group: "{{ nas.user.name }}"
        mode: 0777
      loop:
        - secdev
        - software
        - videos
      tags: nas

- name: prepare mail-based notifications
  include_tasks: mailing.yml
  tags: [ nas, mail, auto-upgrade ]

- name: setup unattended upgrades
  include_tasks: upgrades.yml
  tags: [ nas, auto-upgrade ]

- name: set hostname
  include_tasks: hostname.yml
  tags: nas
