- name: update apt caches
  apt:
    update_cache: yes
  changed_when: no

- name: prepare mount point root
  file:
    path: "{{ mount_base_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: create UNIX users
  include_tasks: users.yml

- name: mount
  include_tasks: mount.yml
  loop: "{{ mounts }}"
  loop_control:
    loop_var: mount
  when: mounts is defined

- name: file permissions
  block:
    - name: file permissions of private shares
      file:
        path: "{{ mount_base_dir }}/{{ mounts[0].name }}/backup/{{ user.smbdir }}"
        state: directory
        owner: "{{ user.name }}"
        group: "{{ user.name }}"
        mode: 0700
        recurse: yes
      loop: "{{ users }}"
      loop_control:
        loop_var: user

    - name: file permissions of public shares
      file:
        path: "{{ mount_base_dir }}/{{ mounts[0].name }}/{{ item }}"
        state: directory
        owner: "{{ nas_user.name }}"
        group: "{{ nas_user.name }}"
        recurse: yes
      loop:
        - secdev
        - software
        - videos

- name: setup mail-based notifications
  include_tasks: mailing.yml

- name: setup unattended upgrades
  include_tasks: upgrades.yml
