- name: unattended upgrades - install
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - unattended-upgrades
    - apt-listchanges

- name: unattended upgrades - configure
  blockinfile:
    path: "/etc/apt/{{ item }}"
    block: "{{ lookup('file', 'etc/apt/{{ item }}') }}"
  loop:
    - apt.conf.d/50unattended-upgrades
    - apt.conf.d/20auto-upgrades
    - listchanges.conf

- name: unattended upgrades - configure timers
  copy:
    src: "etc/systemd/system/{{ item }}/override.conf"
    dest: "/etc/systemd/system/{{ item }}/"
  loop:
    - apt-daily.timer.d
    - apt-daily-upgrade.timer.d
