- name: unattended upgrades - install
  apt:
    name: unattended-upgrades,apt-listchanges
    cache_valid_time: 600

- name: unattended upgrades - configure
  blockinfile:
    path: "/etc/apt/{{ item.path }}"
    block: "{{ lookup(item.type, 'etc/apt/{{ item.path }}{{ item.local_path_suffix | default('') }}') }}"
  loop:
    - { path: apt.conf.d/50unattended-upgrades, type: template, local_path_suffix: .j2 }
    - { path: apt.conf.d/20auto-upgrades, type: file }
    - { path: listchanges.conf, type: template, local_path_suffix: .j2 }

- name: unattended upgrades - configure timers
  copy:
    src: "etc/systemd/system/{{ item }}/override.conf"
    dest: "/etc/systemd/system/{{ item }}/"
  loop:
    - apt-daily.timer.d
    - apt-daily-upgrade.timer.d
