- name: register SSH key of linked realms
  include_tasks: ssh_id_copy.yml
  vars:
    user:
      name: "{{ nas.user.name }}"
      authorized_keys:
        - "{{ nas.authorized_keys }}"

- name: register SSH keys of users
  include_tasks: ssh_id_copy.yml
  with_items: "{{ users }}"
  loop_control:
    loop_var: user

- name: configure
  blockinfile:
    block: "{{ lookup('template', 'sshd_config.j2') }}"
    path: /etc/ssh/sshd_config
    validate: /usr/sbin/sshd -t -f %s
    backup: yes
