- name: copy SSH key for user 'sebschlicht'
  authorized_key:
    user: sebschlicht
    state: present
    key: "{{ lookup('file', 'id_sebschlicht.pub') }}"

- name: configure
  blockinfile:
    block: "{{ lookup('file', 'sshd_config') }}"
    path: /etc/ssh/sshd_config
  register: sshd_config

- name: configure service
  service:
    name: sshd
    state: "{{ 'restarted' if sshd_config.changed else 'started' }}"
    enabled: yes
