- set_fact:
    openvpn_client_key: "{{ openvpn_ca_folder }}/private/{{ openvpn_client.name }}.key"
    openvpn_client_certificate: "{{ openvpn_ca_certificate_folder }}/{{ openvpn_client.name }}.crt"
    openvpn_client_provisioning_folder: "/home/{{ openvpn_client.name }}/openvpn-provisioning"

- name: create client provisioning folder
  file:
    path: "{{ openvpn_client_provisioning_folder }}"
    state: directory
    owner: "{{ openvpn_client.name }}"
    group: "{{ openvpn_client.name }}"

- name: generate client configuration
  template:
    dest: "{{ openvpn_client_provisioning_folder }}/{{ openvpn_client.name }}.ovpn"
    src: openvpn/client.conf
    owner: "{{ openvpn_client.name }}"
    group: "{{ openvpn_client.name }}"
    mode: 0644

- name: copy certificates
  copy:
    src: "{{ item }}"
    dest: "{{ openvpn_client_provisioning_folder }}"
    remote_src: yes
    owner: "{{ openvpn_client.name }}"
    group: "{{ openvpn_client.name }}"
    mode: 0644
  loop:
    - "{{ openvpn_ca_root_certificate }}"
    - "{{ openvpn_client_certificate }}"
    - "{{ openvpn_server_tls_auth_key }}"

- name: create provisioning package
  archive:
    path:
      - "{{ openvpn_client_provisioning_folder }}/*.crt"
      - "{{ openvpn_client_provisioning_folder }}/*.ovpn"
      - "{{ openvpn_client_provisioning_folder }}/ta.key"
    dest: "{{ openvpn_client_provisioning_folder }}/openvn-{{ openvpn_client.name }}.zip"
    format: zip
    remove: yes

- name: provision client key
  copy:
    src: "{{ openvpn_client_key }}"
    dest: "{{ openvpn_client_provisioning_folder }}"
    remote_src: yes
    owner: "{{ openvpn_client.name }}"
    group: "{{ openvpn_client.name }}"
    mode: 0600
