- name: install
  apt:
    name:
      - openvpn
      - easy-rsa
    cache_valid_time: 600

- name: enable IP forwarding
  blockinfile:
    path: /etc/sysctl.conf
    block: |
      net.ipv4.ip_forward = 1
  register: sysctl_config

- name: apply sysctl configuration changes
  command: "sysctl -p"
  when: sysctl_config.changed

- name: create user and group
  user:
    name: openvpn
    create_home: no

- name: create certificates via CA
  include_tasks: ca.yml

- name: deploy and provision client certificates
  include_tasks: client.yml
  loop: "{{ users }}"
  loop_control:
    loop_var: openvpn_client

- name: deploy server certificate and configure server
  include_tasks: server.yml
