- name: install server files
  copy:
    src: "{{ openvpn_ca_folder }}/{{ item.path }}"
    dest: "{{ openvpn_server_folder }}"
    remote_src: yes
    force: yes
    owner: openvpn
    group: openvpn
    mode: "{{ item.mode }}"
  loop:
    - { path: 'ca.crt', mode: '644' }
    - { path: 'crl.pem', mode: '644' }
    - { path: 'dh.pem', mode: '644' }
    - { path: 'ta.key', mode: '600' }
    - { path: "issued/{{ openvpn_server_name }}.crt", mode: '644' }
    - { path: "private/{{ openvpn_server_name }}.key", mode: '600' }

- name: create jail
  file:
    path: "{{ openvpn_server_jail }}/tmp"
    state: directory
    owner: openvpn
    group: openvpn

- name: copy required files to jail
  copy:
    src: "{{ openvpn_server_folder }}/crl.pem"
    dest: "{{ openvpn_server_jail }}/"
    remote_src: yes
    force: yes
    owner: openvpn
    group: openvpn
    mode: preserve

- name: configure server
  template:
    dest: "{{ openvpn_server_folder }}/{{ openvpn_server_name }}.conf"
    src: openvpn/server.conf
  register: openvpn_server_config_task

- name: enable
  service:
    name: "openvpn-server@{{ openvpn_server_name }}"
    state: "{{ (openvpn_server_config_task.changed or openvpn_ca_force_recreation) | ternary('restarted', 'started') }}"
    enabled: yes
