- name: create server certificate and key
  expect:
    command: "{{ easyrsa_exe }} build-server-full {{ openvpn_server_name }} nopass"
    creates: "{{ openvpn_ca_certificate_server }}"
    responses:
      'Enter pass .*': "{{ openvpn.ca_passphrase }}"
  register: openvpn_server_certificate_task

- name: verify certificate chain
  command: "openssl verify -CAfile {{ openvpn_ca_root_certificate }} {{ openvpn_ca_certificate_server }}"
  changed_when: no
  when: openvpn_server_certificate_task.changed

- name: install server files
  copy:
    src: "{{ openvpn_ca_folder }}/{{ item.path }}"
    dest: "{{ openvpn_server_folder }}"
    remote_src: yes
    force: yes
    owner: openvpn
    group: openvpn
    mode: "{{ item.mode }}"
  loop:
    - { path: 'ca.crt', mode: '644' }
    - { path: 'crl.pem', mode: '644' }
    - { path: 'dh.pem', mode: '644' }
    - { path: 'ta.key', mode: '600' }
    - { path: "issued/{{ openvpn_server_name }}.crt", mode: '644' }
    - { path: "private/{{ openvpn_server_name }}.key", mode: '600' }
